services:
  rag_app:
    build: .
    stdin_open: true
    tty: true
    container_name: langchain-rag
    volumes:
      - ./:/workspace
    working_dir: /workspace
  ollama_server:
    image: ollama/ollama
    container_name: ollama_server
    volumes:
      - ollama:/root/.ollama
      - ./ollama/models:/models
    environment:
      - OLLAMA_MODELS=/models
    # ports:
    #   - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
  
volumes:
  ollama:
